### Foundation 1
POST http://localhost:4000/foundations
Content-Type: application/json

{
    "name": "Refugio el Campito",
    "state": "Buenos Aires",
    "city": "Monte Grande",
    "address": "ruta 16 Parc 501",
    "lat": "-34.879850",
    "lng": "-58.417770",
    "telephone_number": "(450) 247-5896",
    "email": "elcampitorefugio@hotmail.com",
    "images": [
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196139/Huellas_folder/images_bq8nfn.png"
    ],
    "website": "https://www.elcampitorefugio.org/",
    "instagram": "https://www.instagram.com/refugioelcampito/",
    "password": "12345"
}

### Foundation 2
POST http://localhost:4000/foundations
Content-Type: application/json

{
    "name": "Gatitos de Palermo",
    "state": "Buenos Aires",
    "city": "Palermo",
    "address": "Godoy Cruz 2851",
    "lat": "-34.577180",
    "lng": "-58.424060",
    "telephone_number": "(240) 824-8794",
    "email": "wotagoy136@falsy.com",
    "images": [
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196176/Huellas_folder/13501833_490423977819735_2259851025882273895_n_khewny.jpg" ]
    "website": null,
    "instagram": "https://www.instagram.com/gatitosdepalermo/?hl=es",
    "password": "12345"
}

### Foundation 3
POST http://localhost:4000/foundations
Content-Type: application/json

{
    "name": "El Campito Felino",
    "state": "Buenos Aires",
    "city": "Belgrano",
    "address": "Aristóbulo del Valle 1365",
    "lat": "-34.535460",
    "lng": "-58.474820",
    "telephone_number": "11-6014-1347",
    "email": "elcampitofelino@yahoo.com",
    "images": [
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196223/Huellas_folder/cabeza-gato-lindo-logo-dibujos-animados-cabeza-gato-bueno-productos-relacionados-cuidado-gatos_487414-292_ppb8mx.webp"
    ],
    "website": "https://www.mibelgrano.com.ar/index.php/2020/08/19/el-campito-felino-de-belgrano/",
    "instagram": "https://www.instagram.com/elcampitofelino/?hl=es",
    "password": "12345"
}

### Foundation 4
POST http://localhost:4000/foundations
Content-Type: application/json

{
    "name": "Naricitas Frias",
    "state": "Buenos Aires",
    "city": "Temperley",
    "address": "Rivadavia 277",
    "lat": "-34.763610",
    "lng": "-58.368260",
    "telephone_number": "+54 9 11 5761-0101",
    "email": "info@naricitasfrias.com.ar",
    "images": [
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196303/Huellas_folder/39229072_440775793085411_3835681862940884992_n_bplolj.jpg"
    ],
    "website": "https://www.naricitasfrias.com.ar/",
    "instagram": null,
    "password": "12345"
}

### Foundation 5
POST http://localhost:4000/foundations
Content-Type: application/json

{
    "name": "Refugio Feliz",
    "state": "Buenos Aires",
    "city": "Moreno",
    "address": "Av. Victorica 4888",
    "lat": "-34.632730",
    "lng": "-58.790210",
    "telephone_number": "1161812944",
    "email": "refugiofelizadopciones@gmail.com",
    "images": [
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196507/Huellas_folder/360685_d863fbdb4fb24d5da0555d0e1550a675_mv2_zqfrvn.webp",
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196507/Huellas_folder/BL4v9x9gTv6GDtJV4idA_p1d9fv755y4O1F6Z_eonhyr.png"
     ],
    "website": "https://refugiofelizoficia.wixsite.com/refugiofeliz/inicio",
    "instagram": "https://www.instagram.com/refugiofelizoficial/?hl=es",
    "password": "12345"
}

### Foundation 6
POST http://localhost:4000/foundations
Content-Type: application/json

{
    "name": "Proyecto 4 patas",
    "state": "Buenos Aires",
    "city": "Caballito",
    "address": "Felipe Vallese 908",
    "lat": "-34.613430",
    "lng": "-58.446190",
    "telephone_number": "(992) 883-3934",
    "email": "info@proyecto4patas.org",
    "images": [
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196576/Huellas_folder/116420315_10158358571546047_911541206074533929_n_m8n2qj.jpg"
    ],
    "website": "https://www.proyecto4patas.org/",
    "instagram": "https://www.instagram.com/proyecto4patas/",
    "password": "12345"
}

### Foundation 7
POST http://localhost:4000/foundations
Content-Type: application/json

{
    "name": "Ayudacan",
    "state": "Buenos Aires",
    "city": "Almagro",
    "address": "Jerónimo Salguero 151",
    "lat": "-34.763520",
    "lng": "-58.391440",
    "telephone_number": "011 15-5617-9472",
    "email": "mascotasenadopcionargentina@gmail.com",
    "images": [
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196618/Huellas_folder/ayudacan_logo_chico-725567_sjamgs.jpg",
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196618/Huellas_folder/ayudacan-favicon-512-300x300_annx7e.png"
    ],
    "website": "https://ayudacan.org/",
    "instagram": "https://www.instagram.com/ayudacan/?hl=es",
    "password": "12345"
}

### Foundation 8
POST http://localhost:4000/foundations
Content-Type: application/json

{
    "name": "Patias Glew",
    "state": "Buenos Aires",
    "city": "Glew",
    "address": "Piedad 124",
    "lat": "-34.887380",
    "lng": "-58.381110",
    "telephone_number": "011 15-3613-2282",
    "email": "patitasglew@hotmail.com",
    "images": [
        "https://res.cloudinary.com/djasy7hxk/image/upload/v1659196664/Huellas_folder/135285580_1147794825654429_2369208977162709237_n_zenqkh.jpg"
    ],
    "website": null,
    "instagram": "https://www.instagram.com/patitasglew/?hl=es",
    "password": "12345"
}