### Pet 1 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Agustin",
    "type": "Perro",
    "images":["https://www.elcampitorefugio.org/imgs/uploaded/780878.jpg"],
    "age": "4 años",
    "gender":"Macho",
    "post_date":"2022-07-18",
    "description":"Agustín llegó al refugio sin un ojito. Es un perro muy mimoso y compañero.",
    "foundation": 1
}

### Pet 2 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Yuki",
    "type": "Gato",
    "images": ["https://i.pinimg.com/564x/7b/ad/d2/7badd22798ebcd391fd43850826c092a.jpg"],
    "age": "2 años",
    "gender": "Hembra",
    "post_date": "2022-07-06",
    "description": "Muchos ya conocerán a nuestra hermosa Yuki. Ella es una gatita rescatada preñada del predio de Palermo hace casi 2 años. Es vif+ y desde su rescate hasta hoy tuvimos diversas consultas y estuvo bajo distintos tratamientos sin éxito, debido a diarreas intermitentes. Hace poco, Yuki comenzó a bajar de peso y el mes pasado tuvimos consulta con Amelia Gisbert, quien la derivó a la gastroenterologa Marta Zubaldía",
    "foundation": 2
}

### Pet 3 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Kali",
    "type": "Gato",
    "images": ["https://www.huellascallejeras.com/wp-content/uploads/2020/10/mila-gato-en-adopcion-6-580x460.jpg"],
    "age": "1 año",
    "gender": "Hembra",
    "post_date": "2022-05-01",
    "description": "Quiero estar pegadita a los humanos todo el tiempo, no vaya a ser que pasen frío! Les hago compañía cuando trabajan, cuando cocinan y hasta cuando duermen.",
    "foundation": 3
}

### Pet 4 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Maple",
    "type": "Gato",
    "images": [ "https://pbs.twimg.com/media/FXBNtjhXkAA87VX?format=jpg"],
    "age": "7 meses",
    "gender": "Macho",
    "post_date": "2018-03-18",
    "description": "Ojitos llegó al borde la muerte, con una sentencia de eutanasia pendiendo sobre su cabeza. Víctima del moquillo y de unas infecciones terribles que, literalmente, se lo estaban comiendo vivo. Estuvo internado 52 días, tiempo durante el cual los veterinarios tuvieron que amputarle las patas y la cola para que pudiera salir adelante. Ojitos, hoy, es un canto a la vida, un símbolo de esperanza, siempre alegre, curioso y con mucho amor para dar.",
    "foundation": 4
}

### Pet 5 
POST http://localhost:4000/pets
Content-Type: application/json

{   
    "name": "Nieve",
    "type": "Gato",
    "images": [ "https://live.staticflickr.com/3227/5869530325_4d079315c8_z.jpg"],
    "age": "1 año",
    "gender": "Hembra",
    "post_date": "2021-07-20",
    "description": "Muchos ya conocerán a nuestra hermosa Nieve. Ella es una gatita rescatada preñada del predio de Palermo hace casi 2 años. Es vif+ y desde su rescate hasta hoy tuvimos diversas consultas y estuvo bajo distintos tratamientos sin éxito, debido a diarreas intermitentes. Hace poco, Yuki comenzó a bajar de peso y el mes pasado tuvimos consulta con Amelia Gisbert, quien la derivó a la gastroenterologa Marta Zubaldía",
    "foundation": 5
}

### Pet 6 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Layza",
    "type": "Perro",
    "images": ["https://http2.mlstatic.com/D_NQ_NP_877565-MLA49738888691_042022-V.jpg"],
    "age": "6 años",
    "gender": "Hembra",
    "post_date": "2022-06-03",
    "description": "El estado de Layza al ingresar al refugio era simplemente impactante. Con una cuerda muy gruesa atada al cuello, llegó con un tumor que había afectado la mandíbula y que estaba desgarrando la piel. Como si fuera poco, Layza era también víctima de una bacteria que estaba alimentándose de su piel y tenía varias infecciones. Poco a poco, luego de extraerle el tumor, empezó a comer alimento sólido y ¡cómo le gustaba! Sus ojos comenzaron a brillar llenos de esperanza. Fue en el refugio que conoció a su mamá, una persona maravillosa que cada sábado le costaba cada vez más dejarla en su canil. Hoy, esta dulzura vive en un hogar hermoso, rodeada del calor de una verdadera familia.",
    "foundation": 6
}

### Pet 7 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Oro",
    "type": "Perro",
    "images": ["https://www.opencity.tv/wp-content/uploads/2020/11/perro.jpg"],
    "age": "8 meses",
    "gender": "Macho",
    "post_date": "2022-01-12",
    "description": "Oro fue rescatado cuando estaba vagando por los alrededores de la autopista camino a Pilar. Las zonas del cuello y de la oreja estaban completamente agusanadas. No podemos ni comenzar a imaginarnos el dolor que seguramente estaba sintiendo en ese momento. Pero después de muchos cuidados, mucha paciencia y, más que nada, toneladas de amor, Oro fue recuperándose hasta llegar a convertirse en un perro bellísimo y fuerte. Hoy, después de tanto dolor, Oro duerme feliz en el calor de un hogar y rodeado de una familia que lo ama como se merece y que no dudó en devolverle la dignidad que jamás debió haber perdido.",
    "foundation": 7
}

### Pet 8 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Bella",
    "type": "Perro",
    "images": ["https://www.elcampitorefugio.org/imgs/uploaded/101103.jpg"],
    "age": "7 años",
    "gender": "Hembra",
    "post_date": "2022-02-07",
    "description": "Bella tiene 7 años, es hembra y está castrada. Es súper buena y dócil, hace un montón está en el refugio y se merece el mejor hogar. Se lleva súper con gatos, niñxs y perros! Si te enamoraste de esta gorda hermosa, contactanos",
    "foundation": 6
}

### Pet 9 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Nina",
    "type": "Gato",
    "images": ["https://img.miwuki.com/a/92SWY3/250"],
    "age": "2 años",
    "gender": "Hembra",
    "post_date": "2021-12-10",
    "description": "Nina se encuentra en adopción responsable. Nina es la madre de todos los bebés que rescatamos de la basura en el mes de febrero junto a su cría. Es una hembra de 2 años que la castramos y ahora está lista para encontrar una familia para toda la vida. Está desparasitada y con pipeta. Le encanta jugar, pide mimos todo el tiempo, se sube a todos lados, es hermosa y un amor de gatita. Si te enamoraste de Nina del amor, contactanos.",
    "foundation": 3
}

### Pet 10 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name":"Saint",
    "type":"Perro",
    "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/American_Bulldog_Tank.jpg/2048px-American_Bulldog_Tank.jpg"],
    "age": "4 años",
    "gender": "Macho",
    "post_date": "2022-04-12",
    "description": "Saint, un bulldog americano, tiene dos balas en su cabeza. Paula Ferreira, veterinaria de una clínica en el oeste, trató a Saint. 'Su estado de vida es totalmente critico, pero creemos que podes salvar su vida', comunicó Ferreyra. Si ustedes pueden ayudarnos a tener algo de dinero y recaudar dinero para él, sería increíble. 'También adoptantes, va a haber una solicitud, así que ayúdanos, por favor, por favor ayúdenos', dijo González",
    "foundation": 4
}

### Pet 11
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Panchito",
    "type": "Perro",
    "images": ["https://adopt-a-pet.s3.amazonaws.com/pet_pictures/assets/000/083/023/home/uploads_2Ff0e51aa6-2e64-4f3a-985f-a0eef0c327e9_2FIMG-20220612-WA0132.jpg"],
    "age": "3 meses",
    "gender": "Macho",
    "post_date": "2022-07-10",
    "description": "Panchito crece saludable, tiene 3 meses, super cariñoso, solo ronronea y pide brazos",
    "foundation": 3
}

### Pet 12 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Balthazar",
    "type": "Perro",
    "images": ["https://www.elcampitorefugio.org/imgs/uploaded/980140.jpg"],
    "age": "7 años",
    "gender": "Macho",
    "post_date": "2021-11-20",
    "description": "Balthazar, es un perro tranquilo. Es super educado y le gusta mucho dormir siesta.",
    "foundation": 1
}

### Pet 13 
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Kronos",
    "type": "Perro",
    "images": ["https://ayudacan.org/wp-content/uploads/2022/01/kronos_portada-300x300.webp"],
    "age": "3 años",
    "gender": "Macho",
    "post_date": "2022-04-09",
    "description": "Kronos es un pequeño animal super cariñoso que le encanta jugar con su pelota.",
    "foundation": 7
}

### Pet 14
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Norbert",
    "type": "Gato",
    "images": ["https://www.cronica.com.ar/__export/1646915258169/sites/cronica/img/2022/03/10/gatos_naranjas_1_crop1646915099563.jpg_139781018.jpg"],
    "age": "5 años",
    "gender": "Macho",
    "post_date": "2022-06-17",
    "description": "Este hermoso gatito está en los bosques de palermo. Se encuentra muy flaquito y solo, pero es super cariñoso. Necesitamos un tránsito para poder sacarlo de ahi, castrarlo, y poder conseguirle un hogar",
    "foundation": 2
}

### Pet 15
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Ahri",
    "type": "Gato",
    "images": ["https://arcadenoe.org/imas/animales/_442/thumbnail_square.jpg?id=1389"],
    "age": "5 meses",
    "gender": "Hembra",
    "post_date": "2022-07-21",
    "description": "Ahri es una gata de apenas 5 meses de edad, que fue abandonado con tres meses. Especialmente sensible, ahora se encuentra en un centro veterinario luchando contra la gran tristeza en la que está sumido que le lleva a no comer ni beber por sus propios medios., pedimos una adopción urgente para ella.",
    "foundation": 5
}

### Pet 16
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Yummi",
    "type": "Gato",
    "images": ["https://pbs.twimg.com/media/FOaQVs2XMAgWNBP?format=jpg&name=large"],
    "age": "8 meses",
    "gender": "Hembra",
    "post_date": "2022-02-13",
    "description": "Yummi, una gatita muy cariñosa de apenas 8 meses a quien le encanta jugar con su bolita de lana, necesita un hogar de tránsito para poder recibir todo el amor que se merece.",
    "foundation": 6
}

### Pet 17
POST http://localhost:4000/pets
Content-Type: application/json

{
    "name": "Paper",
    "type": "Perro",
    "images": ["https://www.elcampitorefugio.org/imgs/uploaded/622486.jpg"],
    "age": "2 años",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "Este lindo perrito que está en el parque Sarmiento. Se encuentra muy flaquito, pero es super amistoso. Necesitamos un tránsito para poder sacarlo de ahi y poder conseguirle un hogar",
    "foundation": 5
}