# @api = https://salva-mi-huella-api.herokuapp.com
@api = http://localhost:4000

### Pet 1 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Agustin",
    "type": "Perro",
    "images":["https://res.cloudinary.com/djasy7hxk/image/upload/v1659119458/Huellas_folder/780878_l3gk2o.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659119458/Huellas_folder/8125_z0yj7g.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659119458/Huellas_folder/120237_gigcu3.jpg"],
    "age": "4 años",
    "gender":"Macho",
    "post_date":"2022-07-18",
    "description":"Agustín llegó al refugio sin un ojito. Es un perro muy mimoso y compañero.",
    "foundation": 1
}

### Pet 2 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Yuki",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659119558/Huellas_folder/7badd22798ebcd391fd43850826c092a_gjz9lk.jpg"],
    "age": "2 años",
    "gender": "Hembra",
    "post_date": "2022-07-06",
    "description": "Muchos ya conocerán a nuestra hermosa Yuki. Ella es una gatita rescatada preñada del predio de Palermo hace casi 2 años. Es vif+ y desde su rescate hasta hoy tuvimos diversas consultas y estuvo bajo distintos tratamientos sin éxito, debido a diarreas intermitentes. Hace poco, Yuki comenzó a bajar de peso y el mes pasado tuvimos consulta con Amelia Gisbert, quien la derivó a la gastroenterologa Marta Zubaldía",
    "foundation": 5
}

### Pet 3 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Kali",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659119615/Huellas_folder/mila-gato-en-adopcion-6-580x460_gdyrev.jpg"],
    "age": "1 año",
    "gender": "Hembra",
    "post_date": "2022-05-01",
    "description": "Quiero estar pegadita a los humanos todo el tiempo, no vaya a ser que pasen frío! Les hago compañía cuando trabajan, cuando cocinan y hasta cuando duermen.",
    "foundation": 3
}

### Pet 4 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Maple",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659119685/Huellas_folder/FXBNtjhXkAA87VX_lewdxc.jpg"],
    "age": "7 meses",
    "gender": "Macho",
    "post_date": "2018-03-18",
    "description": "Ojitos llegó al borde la muerte, con una sentencia de eutanasia pendiendo sobre su cabeza. Víctima del moquillo y de unas infecciones terribles que, literalmente, se lo estaban comiendo vivo. Estuvo internado 52 días, tiempo durante el cual los veterinarios tuvieron que amputarle las patas y la cola para que pudiera salir adelante. Ojitos, hoy, es un canto a la vida, un símbolo de esperanza, siempre alegre, curioso y con mucho amor para dar.",
    "foundation": 4
}

### Pet 5 
POST {{api}}/pets
Content-Type: application/json

{   
    "name": "Nieve",
    "type": "Gato",
    "images": [ "https://res.cloudinary.com/djasy7hxk/image/upload/v1659119720/Huellas_folder/5869530325_4d079315c8_z_yzqpiq.jpg"],
    "age": "1 año",
    "gender": "Hembra",
    "post_date": "2021-07-20",
    "description": "Muchos ya conocerán a nuestra hermosa Nieve. Ella es una gatita rescatada preñada del predio de Palermo hace casi 2 años. Es vif+ y desde su rescate hasta hoy tuvimos diversas consultas y estuvo bajo distintos tratamientos sin éxito, debido a diarreas intermitentes. Hace poco, Yuki comenzó a bajar de peso y el mes pasado tuvimos consulta con Amelia Gisbert, quien la derivó a la gastroenterologa Marta Zubaldía",
    "foundation": 5
}

### Pet 6 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Layza",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659119895/Huellas_folder/470757_rnrh0c.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659119895/Huellas_folder/95189_vyvd8y.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659119895/Huellas_folder/847636_g0aiph.jpg"],
    "age": "6 años",
    "gender": "Hembra",
    "post_date": "2022-06-03",
    "description": "El estado de Layza al ingresar al refugio era simplemente impactante. Con una cuerda muy gruesa atada al cuello, llegó con un tumor que había afectado la mandíbula y que estaba desgarrando la piel. Como si fuera poco, Layza era también víctima de una bacteria que estaba alimentándose de su piel y tenía varias infecciones. Poco a poco, luego de extraerle el tumor, empezó a comer alimento sólido y ¡cómo le gustaba! Sus ojos comenzaron a brillar llenos de esperanza. Fue en el refugio que conoció a su mamá, una persona maravillosa que cada sábado le costaba cada vez más dejarla en su canil. Hoy, esta dulzura vive en un hogar hermoso, rodeada del calor de una verdadera familia.",
    "foundation": 6
}

### Pet 7 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Oro",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120012/Huellas_folder/border-collie-6228625_960_720_jvqgps.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120012/Huellas_folder/Borderkolie_ijkxcl.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120013/Huellas_folder/border-collie-6228622_960_720_qe1yqx.jpg"],
    "age": "8 meses",
    "gender": "Macho",
    "post_date": "2022-01-12",
    "description": "Oro fue rescatado cuando estaba vagando por los alrededores de la autopista camino a Pilar. Las zonas del cuello y de la oreja estaban completamente agusanadas. No podemos ni comenzar a imaginarnos el dolor que seguramente estaba sintiendo en ese momento. Pero después de muchos cuidados, mucha paciencia y, más que nada, toneladas de amor, Oro fue recuperándose hasta llegar a convertirse en un perro bellísimo y fuerte. Hoy, después de tanto dolor, Oro duerme feliz en el calor de un hogar y rodeado de una familia que lo ama como se merece y que no dudó en devolverle la dignidad que jamás debió haber perdido.",
    "foundation": 7
}

### Pet 8 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Bella",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120101/Huellas_folder/748051_npc9fn.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120101/Huellas_folder/532869_pdktqi.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120102/Huellas_folder/409848_bhzdve.jpg"],
    "age": "7 años",
    "gender": "Hembra",
    "post_date": "2022-02-07",
    "description": "Bella tiene 7 años, es hembra y está castrada. Es súper buena y dócil, hace un montón está en el refugio y se merece el mejor hogar. Se lleva súper con gatos, niñxs y perros! Si te enamoraste de esta gorda hermosa, contactanos",
    "foundation": 6
}

### Pet 9 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Nina",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120197/Huellas_folder/250_asclzs.jpg"],
    "age": "2 años",
    "gender": "Hembra",
    "post_date": "2021-12-10",
    "description": "Nina se encuentra en adopción responsable. Nina es la madre de todos los bebés que rescatamos de la basura en el mes de febrero junto a su cría. Es una hembra de 2 años que la castramos y ahora está lista para encontrar una familia para toda la vida. Está desparasitada y con pipeta. Le encanta jugar, pide mimos todo el tiempo, se sube a todos lados, es hermosa y un amor de gatita. Si te enamoraste de Nina del amor, contactanos.",
    "foundation": 3
}

### Pet 10 
POST {{api}}/pets
Content-Type: application/json

{
    "name":"Saint",
    "type":"Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120289/Huellas_folder/986902_dmjc1w.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120288/Huellas_folder/216749_akjanr.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120289/Huellas_folder/921051_paklkb.jpg"],
    "age": "4 años",
    "gender": "Macho",
    "post_date": "2022-04-12",
    "description": "Saint, un bulldog americano, tiene dos balas en su cabeza. Paula Ferreira, veterinaria de una clínica en el oeste, trató a Saint. 'Su estado de vida es totalmente critico, pero creemos que podes salvar su vida', comunicó Ferreyra. Si ustedes pueden ayudarnos a tener algo de dinero y recaudar dinero para él, sería increíble. 'También adoptantes, va a haber una solicitud, así que ayúdanos, por favor, por favor ayúdenos', dijo González",
    "foundation": 4
}

### Pet 11
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Panchito",
    "type": "Perro",
    "images": ["https://adopt-a-pet.s3.amazonaws.com/pet_pictures/assets/000/083/023/home/uploads_2Ff0e51aa6-2e64-4f3a-985f-a0eef0c327e9_2FIMG-20220612-WA0132.jpg"],
    "age": "3 meses",
    "gender": "Macho",
    "post_date": "2022-07-10",
    "description": "Panchito crece saludable, tiene 3 meses, super cariñoso, solo ronronea y pide brazos",
    "foundation": 3
}

### Pet 12 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Balthazar",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120389/Huellas_folder/980140_i9fcfq.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120388/Huellas_folder/62304_ppbbcs.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120389/Huellas_folder/273729_xdjqfg.jpg"],
    "age": "7 años",
    "gender": "Macho",
    "post_date": "2021-11-20",
    "description": "Balthazar, es un perro tranquilo. Es super educado y le gusta mucho dormir siesta.",
    "foundation": 1
}

### Pet 13 
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Kronos",
    "type": "Perro",
    "images": ["https://www.refugiodontorcuato.com/images/animales/RECORTAR-81.jpg","https://www.refugiodontorcuato.com/images/animales/RECORTAR-79.jpg", "https://www.refugiodontorcuato.com/images/animales/RECORTAR-82.jpg"],
    "age": "3 años",
    "gender": "Macho",
    "post_date": "2022-04-09",
    "description": "Kronos es un pequeño animal super cariñoso que le encanta jugar con su pelota.",
    "foundation": 7
}

### Pet 14
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Norbert",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120473/Huellas_folder/gatos_naranjas_1_crop1646915099563.jpg_139781018_lrk6vv.webp"],
    "age": "5 años",
    "gender": "Macho",
    "post_date": "2022-06-17",
    "description": "Este hermoso gatito está en los bosques de palermo. Se encuentra muy flaquito y solo, pero es super cariñoso. Necesitamos un tránsito para poder sacarlo de ahi, castrarlo, y poder conseguirle un hogar",
    "foundation": 2
}

### Pet 15
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Ahri",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120508/Huellas_folder/thumbnail_square_krlpbu.jpg"],
    "age": "5 meses",
    "gender": "Hembra",
    "post_date": "2022-07-21",
    "description": "Ahri es una gata de apenas 5 meses de edad, que fue abandonado con tres meses. Especialmente sensible, ahora se encuentra en un centro veterinario luchando contra la gran tristeza en la que está sumido que le lleva a no comer ni beber por sus propios medios., pedimos una adopción urgente para ella.",
    "foundation": 5
}

### Pet 16
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Yummi",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120561/Huellas_folder/FOaQVs2XMAgWNBP_bqbrml.jpg"],
    "age": "8 meses",
    "gender": "Hembra",
    "post_date": "2022-02-13",
    "description": "Yummi, una gatita muy cariñosa de apenas 8 meses a quien le encanta jugar con su bolita de lana, necesita un hogar de tránsito para poder recibir todo el amor que se merece.",
    "foundation": 6
}

### Pet 17
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Paper",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120613/Huellas_folder/188339_aogd9g.jpg","https://res.cloudinary.com/djasy7hxk/image/upload/v1659120614/Huellas_folder/663546_x6tovs.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120614/Huellas_folder/622486_ahqpdx.jpg"],
    "age": "2 años",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "Este lindo perrito que está en el parque Sarmiento. Se encuentra muy flaquito, pero es super amistoso. Necesitamos un tránsito para poder sacarlo de ahi y poder conseguirle un hogar",
    "foundation": 5
}

### Pet 18
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Cofler",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120728/Huellas_folder/Cofler-1_qrdiza_uph0ue.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120729/Huellas_folder/Cofler-3_xsyldk_dedqy5.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120729/Huellas_folder/Cofler-2_lhtab7_jxkmqp.png"],
    "age": "2 años",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "Mushu es un bebé de 4 meses y medio, ya está desparasitado, hace sus necesidades en las piedritas y espera a que lo elijas❣️. En poquitos días se queda sin tránsito 🙏🏻, nuestro mayor deseo es que ya pueda irse a una casita definitiva! Si cumplís con los requisitos y querés sumarlo a hogar dejanos un mensajito privado💌",
    "foundation": 3
}

### Pet 19
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Hanabi",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120845/Huellas_folder/Hanabi-1_s99mwh_qzmeim.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120845/Huellas_folder/Hanabi-2_p9yoml_bmld5s.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120847/Huellas_folder/Hanabi-3_sdrke3_navkwn.png"],
    "age": "2 años",
    "gender": "Hembra",
    "post_date": "2022-06-13",
    "description": "¿Cómo no enamorarse de este pompón blanco? ❤️❤️❤️ Hanabi tiene 2 meses y medio, ya está desparasitada y hace sus necesidades en las piedritas 💪🏻 Si te enamoraste de ella y querés sumarla a tu familia dejanos un mensajito💌",
    "foundation": 2
}

### Pet 20
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Humito",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659120951/Huellas_folder/Humito-3_qlyign_xc89ql.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120952/Huellas_folder/Humito-1_hmjkwe_tr0j9e.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659120952/Huellas_folder/Humito-2_jen9qo_nduaka.png"],
    "age": "3 meses",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "TRÁNSITO URGENTE - se quedan en la calle ‼️‼️‼️ Nuestra panterita se queda sin tránsito el lunes que viene y NO tenemos a dónde llevarlos!!!! Tiene aprox. 3 meses, necesitamos tránsito en una casa en dónde no haya otros gatitos, ya que estamos esperando el resultado de unos análisis.",
    "foundation": 3
}

### Pet 21
POST {{api}}/pets
Content-Type: application/json

{
    "name": "José",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659121099/Huellas_folder/Jos%C3%A9-1_oav0hw_qkqykq.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121100/Huellas_folder/Jos%C3%A9-2_agatlv_yf4jtb.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121101/Huellas_folder/Jose-3_dgrrza_czwgyk.png"],
    "age": "3 meses",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "Este bombón tiene aprox. 2 meses y está desparasitado. Si te gustan los michis mimosos, besadores y abrazadores profesionales, José es tu michi ideal. Si te enamoraste de él y querés sumarlo a tu familia dejanos un mensajito💌",
    "foundation": 2
}

### Pet 22
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Kotaro",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659121193/Huellas_folder/Kotaro-3_vhm1eq_geekco.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121194/Huellas_folder/Kotaro-1_cfd1bj_yxst2c.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121194/Huellas_folder/Kotaro-2_ls81eb_ir7yrw.png"],
    "age": "4 meses",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "¿Cómo resistirse a éste bebote peludo?🥰 Kotaro tiene aprox. 3 meses, está desparasitado y hace sus necesidades en las piedritas💪🏻 Si enamoraste de él y querés adoptarlo dejanos mensajito privado💌",
    "foundation": 2
}

### Pet 23
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Leia",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659121307/Huellas_folder/Sven-3_a3sm4x_zr4fys.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121307/Huellas_folder/Sven-2_nz4hgd_c1txic.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121308/Huellas_folder/Sven-1_yetosn_n0kgwj.png"],
    "age": "4 meses",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "¿Cómo resistirse a ésta bombona peluda?🥰 Leia tiene aprox. 4 meses, está desparasitada y hace sus necesidades en las piedritas💪🏻 Si enamoraste de ella y querés adoptarla dejanos mensajito privado💌",
    "foundation": 2
}

### Pet 24
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Zafira",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659121491/Huellas_folder/Zafira-1_yibcwp_iumzll.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121492/Huellas_folder/Zafira-2_ojrhkf_h83nl4.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121492/Huellas_folder/Zafira-3_rkrahx_oopdih.png"],
    "age": "1 año",
    "gender": "Hembra",
    "post_date": "2022-06-13",
    "description": "Imposible resistirse a ella y a su carita que es todo un arte😍🎨 Zafi tiene 1 año, YA ESTÁ CASTRADA, desparasitada y hace sus necesidades en las piedritas💪🏻 Si te enamoraste de ella y querés sumarla a tu familia dejanos un mensajito privado💌",
    "foundation": 2
}

### Pet 25
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Batman",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659121606/Huellas_folder/Batman-1_tborhd_nibav5.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121605/Huellas_folder/Batman-2_lb34ol_cgtntf.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121605/Huellas_folder/Batman-3_pndhz8_k66qwc.png"],
    "age": "6 años",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "Soy macho, un poco grande, serio, pero puedo hacerte una gran compañía (y mi nombre es genial).",
    "foundation": 1
}

### Pet 26
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Abel",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659121728/Huellas_folder/Abel_-1_jjrpr7_urwyto.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121729/Huellas_folder/Abel-2_yu7d1r_ywnrbk.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121730/Huellas_folder/Abel-3_zotu70_cicpmi.png"],
    "age": "4 años",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "Tengo mucha energía, amo jugar, puedo ser un poco bruto pero lo compenso con mucho amor. Me llevo muy bien con chicos y otros perros",
    "foundation": 1
}

### Pet 27
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Abrojo",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659121813/Huellas_folder/Abrojo-1_qidjkk_hqoybz.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121812/Huellas_folder/Abrojo-2_dnmbca_rrqllc.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121812/Huellas_folder/Abrojo-3_lmfdbe_bssz9y.png"],
    "age": "2 años",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "Soy un perro blanco, de tamaño mediano, y soy excelente compañía para mirar pelis y series. Me llevo muy buen con chicos.",
    "foundation": 1
}


### Pet 28
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Bianca",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659121909/Huellas_folder/Bianca-2_kunvxn_tzuds2.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121911/Huellas_folder/Bianca-1_q1pxzn_ur1byo.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121911/Huellas_folder/Bianca-3_nvo3gt_gxjnst.png"],
    "age": "1 año",
    "gender": "Hembra",
    "post_date": "2022-06-13",
    "description": "Si bien mis patitas me fallaron, tengo mucha energía y estoy lista para ser tu mejor compañía, hasta me puse un pañuelo para salir más linda en las fotos!",
    "foundation": 1
}

### Pet 29
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Uma",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659121988/Huellas_folder/Braulio-3_yw4yl2_rxefdf.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121989/Huellas_folder/Braulio-1_yknkv8_l59wy1.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659121990/Huellas_folder/Braulio-2_phmaqb_n62tox.png"],
    "age": "8 meses",
    "gender": "Hembra",
    "post_date": "2022-06-13",
    "description": "Tengo un tamaño grande, me gusta la calma y la serenidad. ¡Soy ideal para la siesta! Me llevo bien con chicos y con otros perros.",
    "foundation": 1
}

### Pet 30
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Jade",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659122081/Huellas_folder/Jade-3_rfdvii_gfkvuv.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122081/Huellas_folder/Jade-1_ast7wc_onxbnu.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122083/Huellas_folder/Jade-2_qk0cfl_o94nwm.png"],
    "age": "5 años",
    "gender": "Hembra",
    "post_date": "2022-06-13",
    "description": "Mi tamaño es mediano, tengo un pelaje color beige y soy muy tranquilo. Me llevo muy bien con chicos y con otros perros.",
    "foundation": 1
}

### Pet 31
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Garfiel",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659122185/Huellas_folder/Sin_t%C3%ADtuloa_tu96mr_vbueya.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122185/Huellas_folder/Sin_t%C3%ADtualo_k833yt_rdqyxx.png"],
    "age": "1 año y medio",
    "gender": "Macho",
    "post_date": "2022-07-13",
    "description": "Hermoso gato macho de 1 año y medio, esta castrado, con vacunas, es bueno y sociable, esta en tránsito pero muy pronto se acabará, deberá venir al refugio, donde padecerá frío y no es lo ideal luego de estar en un departamento por eso ayudanos ",
    "foundation": 2
}

### Pet 32
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Rolo",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659122273/Huellas_folder/Sin_t%C3%ADtuloasas_ravawq_ta01nq.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122274/Huellas_folder/Sin_t%C3%ADtulsao_s6ke4d_w8egs5.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122275/Huellas_folder/Sin_tsasas%C3%ADtulo_ot38x5_cpwazz.png"],
    "age": "5 años",
    "gender": "Macho",
    "post_date": "2022-07-15",
    "description": "Si existiera el campeonato de sacadas de lengua👅no tenemos duda de que Rolo sería el campeón 🏆ADOPTÁ a Rolito. Kilos de amor y besos asegurados🤗",
    "foundation": 1
}

### Pet 33
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Paquito",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659122362/Huellas_folder/Sin_t%C3%ADtulsaas_mrqr5n_w8qvub.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122363/Huellas_folder/Sin_t%C3%ADtasaeulo_cwhxc9_azf5cx.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122364/Huellas_folder/Sin_t%C3%ADtaulo_ywjwtw_fnmjzo.png"],
    "age": "5 meses",
    "gender": "Perro",
    "post_date": "2022-07-17",
    "description": "Mirá la evolución de Paquito y decinos sino está %100 recuperado como para tener un hogar definitivo🏠🐶Dale una oportunidad a un rescatado. ADOPTÁ a Paquito🙌",
    "foundation": 1
}

### Pet 34
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Ramoncito",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659122500/Huellas_folder/Sin_tewe%C3%ADtulo_uyoczy_llbazh.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122501/Huellas_folder/Sin_t%C3%ADtulasaso_to2kf0_cl4dze.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122501/Huellas_folder/Sin_t%C3%ADtassasulo_pahyc4_ah7hpf.png"],
    "age": "4 meses",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "Gatito de 4 meses divino mimoso con vacunas",
    "foundation": 2
}

### Pet 35
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Derek",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659122585/Huellas_folder/Sin_t%C3%ADtualo_gu1zhh_dwulql.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122586/Huellas_folder/Sin_t%C3%ADtasdulo_m1biwz_wybf5m.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122587/Huellas_folder/Sin_t%C3%ADtulo_kllqk8_e0y1qh.png"],
    "age": "1 año y medio",
    "gender": "Macho",
    "post_date": "2022-07-01",
    "description": "DEREK machito de 1 AÑO Y MEDIO, castrado, con vacunas, se lleva muy bien con perros. Es dócil y muy sociable",
    "foundation": 3
}

### Pet 36
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Panchito",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659122686/Huellas_folder/Sin_st%C3%ADtulo_ldc7gp_v5rcpe.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122686/Huellas_folder/Sin_t%C3%ADtdulo_oh5nkd_ur7q4j.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122687/Huellas_folder/Sin_t%C3%ADsatulo_ircrsk_wevygx.png"],
    "age": "3 meses",
    "gender": "Macho",
    "post_date": "2022-07-13",
    "description": "Panchito crece saludable, tiene 3 meses, super cariñoso, solo ronronea y pide brazos!!!",
    "foundation": 3
}

### Pet 37
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Zeke",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/huellitas2/image/upload/v1659036173/Huellas_folder/Sin_t%C3%ADtulo_z5vuek.png", "https://res.cloudinary.com/huellitas2/image/upload/v1659036171/Huellas_folder/Sin_t%C3%ADtuslo_yojbyy.png", "https://res.cloudinary.com/huellitas2/image/upload/v1659036172/Huellas_folder/Sin_t%C3%ADtuslaso_mezpxq.png"],
    "age": "2 meses",
    "gender": "Macho",
    "post_date": "2022-07-15",
    "description": "Hace exactamente un mes alguien abandonaba a 7 cachorros indefensos, mojados y helados dentro de bolsas colgadas sigilosamente en las rejas de varias casas de un mismo barrio💔Los fuimos recibiendo a medida que nos avisaban y dándole atención. Todos necesitaron internación y tristemente una bebita murió sin que se pudiera hacer nada para evitarlo. Los otros pudieron salir adelante y hoy están todos felizmente adoptados excepto Zeke que aun espera ser elegido.Es un cachorro hermoso y sano con muchísimo amor para dar.Dale una oportunidad a Zeke.",
    "foundation": 4
}

### Pet 38
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Jack",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659122797/Huellas_folder/s_s5rqnj_cqcgk6.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122798/Huellas_folder/Sinas_t%C3%ADtulo_k5bmub_mxsvsr.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122798/Huellas_folder/Sin_tsa%C3%ADtulo_zvt89x_bykft4.png"],
    "age": "3 meses",
    "gender": "Macho",
    "post_date": "2022-07-11",
    "description": "Jack y sus 4 hermanitos fueron rescatados de la casa de una acumuladora de gatos.Todos tenían infecciones respiratorias y oculares, pero Jack tenia un ojo ulcerado muy comprometido y no se pudo hacer nada para salvarlo😔Como consecuencia de esto quedó con un ojo atrofiado pero eso no le impide llevar una vida normal y ser un gatito hermoso y activoTodos sus hermanitos consiguieron familia salvo Jack, que aun no encontró a su humano ideal que pueda ver mas allá de las diferencias😻Tiene 3 meses y goza de buena salud.",
    "foundation": 4
}

### Pet 39
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Mandy",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659122897/Huellas_folder/asas_lis4cu_gmiubi.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122897/Huellas_folder/Sin_t%C3%ADtusaclo_mbgthl_z50yvd.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659122897/Huellas_folder/Sin_t%C3%ADtaasxulo_ohasdu_epqz8o.png"],
    "age": "1 año y medio",
    "gender": "Hembra",
    "post_date": "2022-06-26",
    "description": "No podíamos elegir solo una foto porque salió hermosa en todas🤩🤔Pero hay algo que no podemos entender,¿Como Mandy sigue sin ser adoptada?👉Si querés sumarla a tu familia mándanos una solicitud ",
    "foundation": 5
}

### Pet 40
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Claudia",
    "type": "Gato",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659123008/Huellas_folder/Sin_t%C3%ADtqwrulo_e3louy_zwbopo.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123010/Huellas_folder/Sin_t%C3%ADtswqulo_c6hs4l_crhct3.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123010/Huellas_folder/Sin_sasasw_t1lpag_uqzyba.png"],
    "age": "1 año",
    "gender": "Hembra",
    "post_date": "2022-07-11",
    "description": "Claudia es tan buena y dócil. Esta hace tiempo esperando hogar, esterilizada, tiene 1 año,",
    "foundation": 5
}

### Pet 41
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Isaac",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659123114/Huellas_folder/Sin_t%C3%ADtwrgulo_wwqukp_wsljzo.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123114/Huellas_folder/Sin_tsaw%C3%ADtulo_dj6ysm_zdqeli.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123115/Huellas_folder/Sin_t%C3%ADtusawlo_cag9rs_gdnh9w.png"],
    "age": "5 meses",
    "gender": "Macho",
    "post_date": "2022-07-21",
    "description": "Imagínate llegar a tu casa y que Isaac te esté esperando así 🤗Este pequeño orejón de 5 meses está en adopción y vos podrías ser su humanx🙋Está desparasitado y con su plan de vacunación completo💉",
    "foundation": 6
}

### Pet 42
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Olga",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659123197/Huellas_folder/Sin_t%C3%ADswtulo_hhcxv7_pdebui.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123197/Huellas_folder/Sin_t%C3%ADtuswtlo_ciqlxw_me4fzh.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123199/Huellas_folder/Sin_t%C3%ADtrulo_av3jdy_orvoc4.png"],
    "age": "10 años",
    "gender": "Hembra",
    "post_date": "2022-06-13",
    "description": "Tenemos un sueño, queremos que Olguita tenga un hogar. Es una viejita ciega que rescatamos de la calle😔 Unos vecinos le habían puesto una caja para que no se mueva y corra peligro con los autos, pero la calle no es hogar para nadie y menos para una perrita que no puede ver📦¿Se imaginan la desesperación?🥺",
    "foundation": 6
}

### Pet 43
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Lazaro",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659123293/Huellas_folder/lazaro_portada_sxukqk.webp", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123293/Huellas_folder/lazaro_9_c72nwu.webp", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123293/Huellas_folder/lazaro_10_anr91b.webp"],
    "age": "5 años",
    "gender": "Macho",
    "post_date": "2022-07-25",
    "description": "Lazaro es el perro mas especial que tenemos ayudacan, esta esperando por ser adoptado, el espera por vos",
    "foundation": 7
}

### Pet 44
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Pamba",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659123376/Huellas_folder/pampa_portada_ddamfs.webp", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123377/Huellas_folder/pampa_15_fppmcr.webp", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123378/Huellas_folder/pampa_14_vbjyjf.webp"],
    "age": "5 años",
    "gender": "Macho",
    "post_date": "2022-06-13",
    "description": "Llego muy flaquito pero aca se esta recuperando y dejando atras el pasado. Pamba quiere ser adoptado esta esperando por ti",
    "foundation": 7
}

### Pet 45
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Miel",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659123517/Huellas_folder/Sin_tsawwq%C3%ADtulo_mco6ku_mfmtqu.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123517/Huellas_folder/Sin_t%C3%ADswtulo_rhf0bk_qmaqn4.png", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123517/Huellas_folder/Sin_t%C3%ADtusawwlo_xdz7tq_d1byuk.png"],
    "age": "3 meses",
    "gender": "Hembra",
    "post_date": "2022-06-29",
    "description": "Miel fue brutalmente atacada por otro perro que le ocasionó una fractura de craneo a sus 2 meses de vida. Sus chances de sobrevivir no eran muchas, pero había que intentarlo..Con el tratamiento indicado y los cuidados de su tránsito ella logró salir adelante y hoy después de una larga lucha ya se encuentra totalmente recuperada y lista para encontrar su familia definitiva.Vos qué esperas para sumarla a tu manada?",
    "foundation": 8
}

### Pet 46
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Mora",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659124075/Huellas_folder/Sky-Fundacion-Adopta-No-Compres_oi8s7b.jpg", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659124075/Huellas_folder/Gaspar-Fundacion-Adopta-No-Compres_lvzsnj.jpg"],
    "age": "5 meses",
    "gender": "Hembra",
    "post_date": "2022-06-30",
    "description": "Primero mírate todas las fotos 📷 y después decinos si Mora no es la cachorrona más hermosa de Instagram🤩Sus hermanos fueron adoptados pero ella sigue esperando una familia con quien jugar😀Tiene 5 meses y está vacunada. Lista para irse a su nuevo hogar🏠",
    "foundation": 8
}

### Pet 47
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Kronos",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659123699/Huellas_folder/kronos_portada_y4frok.webp", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123700/Huellas_folder/kronos_12_vzmts9.webp", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123702/Huellas_folder/kronos_13_gcv6uz.webp"],
    "age": "3 años",
    "gender": "Macho",
    "post_date": "2022-07-01",
    "description": "Lo que mas le gusta es salir a pasear, le cuetas hacerse amigo de otros perros. Espera por ti",
    "foundation": 7
}

### Pet 48
POST {{api}}/pets
Content-Type: application/json

{
    "name": "Dj",
    "type": "Perro",
    "images": ["https://res.cloudinary.com/djasy7hxk/image/upload/v1659123779/Huellas_folder/dj_portada_volw5c.webp", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123779/Huellas_folder/dj_7_i6nssr.webp", "https://res.cloudinary.com/djasy7hxk/image/upload/v1659123781/Huellas_folder/dj_16_swuu9e.webp"],
    "age": "2 años",
    "gender": "Macho",
    "post_date": "2022-07-25",
    "description": "Necesita un hogar sin niños ni gatos, es muy energico y mimoso aunque un poco torpe demostrando su cariño",
    "foundation": 7
}